baseURL = 'https://elocowan.github.io/'
languageCode = 'en-us'
title = 'Ethan Cowan'
enableGitInfo = true

[params]
name = 'Ethan Cowan'

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
